### PR TITLE
:bug: fix v3 finalUrl

### PR DESCRIPTION
**Pull request by thierrymichel**
add missing '&' before query string

### CODE REVIEW

**Comment by leocabeza** [comment]
Hi @thierrymichel. Nice catch, but I think the right fix is putting this '&' in line 44 (https://github.com/leocabeza/the-movie-db/pull/53/files#diff-be73193a7de1c86c1903f5cf92321d2aL44) after `api_key=${v3Key}`

so this line would finally be:

```let finalUrl = usev4 ? originalUrl : `${originalUrl}api_key=${v3Key}&`;```

What do you think?

**Comment by thierrymichel** [comment]
Hi @leocabeza,

TBH, I first put it there. Then I saw the line with `concat` and `queryString` and changed my mind.
I would say that it's up to you. 😁
I can make the change…

**Comment by leocabeza** [comment]
Yes, please, if you can do it I can merge it @thierrymichel

**Comment by thierrymichel** [comment]
@leocabeza  👍

**Comment by leocabeza** [comment]
Thanks again @thierrymichel

**Pull request merged**
